name: CI

on: [push, pull_request]

jobs:
  Tests:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install LilyPond
      run: |
        brew install nwhetsell/lilypond/lilypond-unstable
        brew link lilypond-unstable

    - name: Create PDFs
      run: |
        for folder in chord-diagrams excerpts exercises scale-diagrams; do
          cd $folder
          find . -name '*.ly' -exec lilypond {} \;
          find . -name '*.cropped.pdf' -exec sh -c 'mv -f "$1" $(basename "$1" .cropped.pdf).pdf' sh {} \;
          rm -f *.png
          cd ..
        done
