name: CI

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install LilyPond
      run: |
        wget --no-verbose https://lilypond.org/download/binaries/linux-64/lilypond-2.22.1-1.linux-64.sh
        sudo sh lilypond-2.22.1-1.linux-64.sh --batch

    - name: Create PDFs
      run: |
        lilypond chord-diagrams/b-flat-7-sharp-11.ly
        lilypond chord-diagrams/e-half-diminished-7.ly
        lilypond exercises/cory-wong-arpeggios.ly
        lilypond exercises/descending-16ths.ly
        lilypond exercises/Dm7-arpeggio.ly
        lilypond exercises/dorian-shifting.ly
        lilypond exercises/sequence-1.ly
        lilypond exercises/shifting-gears.ly
        lilypond exercises/spider.ly
        lilypond scale-diagrams/albert-king-box.ly
        lilypond scale-diagrams/blues-scale-shifts.ly
        lilypond scale-diagrams/dominant-7-arpeggio.ly
        lilypond scale-diagrams/dorian-position-5.ly
        lilypond scale-diagrams/major-pentatonic-positions.ly
        lilypond scale-diagrams/major-scale-modes-2-notes-on-string-3.ly
        lilypond scale-diagrams/major-scale-modes-from-pentatonic-positions.ly
        lilypond scale-diagrams/minor-pentatonic-positions.ly
        lilypond scale-diagrams/phrygian-dominant.ly
