name: CI

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install LilyPond
      run: |
        wget --no-verbose https://lilypond.org/download/binaries/linux-64/lilypond-2.22.1-1.linux-64.sh
        sudo sh lilypond-2.22.1-1.linux-64.sh --batch

    - name: Create PDFs
      run: |
        cd chord-diagrams
        lilypond b-flat-7-sharp-11.ly
        lilypond e-half-diminished-7.ly
        cd ../excerpts
        lilypond 'Do You Feel Like We Do.ly'
        cd ../exercises
        lilypond cory-wong-arpeggios.ly
        lilypond descending-16ths.ly
        lilypond Dm7-arpeggio.ly
        lilypond dorian-shifting.ly
        lilypond ii-V-I-licks.ly
        lilypond sequence-1.ly
        lilypond shifting-gears.ly
        lilypond spider.ly
        cd ../scale-diagrams
        lilypond albert-king-box.ly
        lilypond b-b-king-box.ly
        lilypond blues-scale-shifts.ly
        lilypond dominant-7-arpeggio.ly
        lilypond dorian-position-5.ly
        lilypond major-pentatonic-positions.ly
        lilypond major-scale-modes-2-notes-on-string-3.ly
        lilypond major-scale-modes-from-pentatonic-positions.ly
        lilypond minor-pentatonic-positions.ly
        lilypond minor-scales.ly
        lilypond phrygian-dominant.ly
